<?php
/**
 * TL_ROOT/system/modules/avatar/languages/de/tl_settings.php 
 * 
 * TYPOlight extension: avatar 0.1.0 beta1 
 * German translation file 
 * 
 * Copyright : (c) 2008 IBK Software AG 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://contifex.com 
 * Translator: Peter Koch (acenes), http://contifex.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['dokmansystem_legend'] = "Dokumenten Management System";
$GLOBALS['TL_LANG']['tl_settings']['dokmansystem_dir']['0'] = "Basisverzeichnis";
$GLOBALS['TL_LANG']['tl_settings']['dokmansystem_dir']['1'] = "Basisverzeichnis für Dokumente auswählen. Der empfohlene Ort is <em>tl_files/dokmandateien</em>.";

$GLOBALS['TL_LANG']['tl_settings']['dokmansystem_struktur']['0'] = "Kategoriestruktur ein/-ausblenden";
$GLOBALS['TL_LANG']['tl_settings']['dokmansystem_struktur']['1'] = "Soll die Kategoriestruktur immer eingeblendet sein?"; 

$GLOBALS['TL_LANG']['tl_settings']['dokmansystem_kategorieausblenden']['0'] = "leere/gesperrte Kategorien ein/-ausblenden";
$GLOBALS['TL_LANG']['tl_settings']['dokmansystem_kategorieausblenden']['1'] = "Sollen leere und gesperrte Kategorien eingeblendet werden?"; 

?>
